services:
  app:
    build: ./
    volumes:
      - ./src:/var/www
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 8020:80
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
